#Python data types
#........non numeri.......
#1..str ...string...
a ="hello"
print(a)
print(type(a))
#2..bool...boolean...
b=False
print(b)
print(type(b))
#........non numeri.......
#1..str ...string...
